spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    generate-ddl: true
  datasource:
    username: insurance_user
    password: password
    url: jdbc:postgresql://localhost:5432/insurance?createDatabaseIfNotExist=true